
 class Versiculos{

  static List Wordpass = [
    "Consequentemente, a fé vem por se ouvir a mensagem, e a mensagem é ouvida mediante a palavra de Cristo. Romanos 10:17",
    "Porque vivemos por fé, e não pelo que vemos. 2º Coríntios 5:7",
    "Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos.  Hebreus 11:1",
    "Estejam vigilantes, mantenham-se firmes na fé, sejam homens de coragem, sejam fortes. 1º Coríntios 16:13",
    "pois vocês sabem que a prova da sua fé produz perseverança. Tiago 1:3",
    "mantendo a fé e a boa consciência que alguns rejeitaram e, por isso, naufragaram na fé. 1º Timóteo 1:19",
    "Por isso, vos digo que tudo o que pedirdes, orando, crede que o recebereis e tê-lo-eis. Marcos 11:24",
    "Porque andamos por fé e não por vista. 2º Coríntios 5:7",
    "Disse-lhe Jesus: Não te hei dito que, se creres, verás a glória de Deus? João 11:40",
    "E Jesus disse-lhe: Se tu podes crer; tudo é possível ao que crê. Marcos 9:23",
    "Sabendo que a prova da vossa fé produz a paciência. Tiago 1:3",
    "E tudo o que pedirdes na oração, crendo, o recebereis.  Mateus 21:22",
    "Agora, pois, permanecem a fé, a esperança e o amor, estes três; mas o maior destes é o amor. 1º Coríntios 13:13",
    "Assim também a fé, se não tiver as obras, é morta em si mesma. Tiago 2:17",
    "Se, com a tua boca, confessares ao Senhor Jesus e, em teu coração, creres que Deus o ressuscitou dos mortos, serás salvo. Romanos 10:9",
    "Àquele que não conheceu pecado, o fez pecado por nós; para que, nele, fôssemos feitos justiça de Deus. 2 Coríntios 5:21",
    "Assim que, se alguém está em Cristo, nova criatura é: as coisas velhas já passaram; eis que tudo se fez novo. 2 Coríntios 5:17",
    "Assim resplandeça a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem o vosso Pai, que está nos céus. Mateus 5:16",
    "Bem-aventurado o varão que sofre a tentação; porque, quando for provado, receberá a coroa da vida, a qual o Senhor tem prometido aos que o amam. Tiago 1:12",
    "Como o orvalho do Hermom, que desce sobre os montes de Sião; porque ali o Senhor ordena a bênção e a vida para sempre. Salmos 133:3",
    "Confessai as vossas culpas uns aos outros e orai uns pelos outros, para que sareis; a oração feita por um justo pode muito em seus efeitos. Tiago 5:16",
    "Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento. Provérbios 3:5",
    "Conhecemos o amor nisto: que ele deu a sua vida por nós, e nós devemos dar a vida pelos irmãos. 1 João 3:16",
    "Contra essas coisas não há lei. Gálatas 5:23",
    "De sorte que a fé é pelo ouvir, e o ouvir pela palavra de Deus. Romanos 10:17",
    "Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize. João 14:27",
    "Deleita-te também no Senhor, e ele te concederá o que deseja o teu coração. Salmos 37:4",
    "Disse-lhe Jesus: Eu sou a ressurreição e a vida; quem crê em mim, ainda que esteja morto, viverá. João 11:25",
    "Disse-lhe Jesus: Eu sou o caminho, e a verdade, e a vida. Ninguém vem ao Pai senão por mim. João 14:6",
    "E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus. Filipenses 4:7",
    "É como o óleo precioso sobre a cabeça, que desce sobre a barba, a barba de Arão, e que desce à orla das suas vestes. Salmos 133:2",
    "E criou Deus o homem à sua imagem; à imagem de Deus o criou; macho e fêmea os criou. Gênesis 1:27",
    "E disse o Senhor, em visão, a Paulo: Não temas, mas fala e não te cales. Atos 18:9",
    "E disse-lhes Pedro: Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo para perdão dos pecados, e recebereis o dom do Espírito Santo. Atos 2:38",
    "E em nenhum outro há salvação, porque também debaixo do céu nenhum outro nome há, dado entre os homens, pelo qual devamos ser salvos. Atos 4:12",
    "E ficou ali um ano e seis meses, ensinando entre eles a palavra de Deus. Atos 18:11",
    "E Jesus disse-lhe: Amarás o Senhor, teu Deus, de todo o teu coração, e de toda a tua alma, e de todo o teu pensamento. Mateus 22:37",
    "E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus, daqueles que são chamados por seu decreto. Romanos 8:28",
    "E, chegando-se Jesus, falou-lhes, dizendo: É-me dado todo o poder no céu e na terra. Mateus 28:18",
    "E, tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor e não aos homens. Colossenses 3:23",
    "Ensinando-as a guardar todas as coisas que eu vos tenho mandado; e eis que eu estou convosco todos os dias, até à consumação dos séculos. Amém! Mateus 28:20",
    "Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós. 1 Pedro 5:7",
    "Mas a todos quantos o receberam deu-lhes o poder de serem feitos filhos de Deus: aos que creem no seu nome. João 1:12",
    "Mas buscai primeiro o Reino de Deus, e a sua justiça, e todas essas coisas vos serão acrescentadas. Mateus 6:33",
    "Mas Deus prova o seu amor para conosco em que Cristo morreu por nós, sendo nós ainda pecadores. Romanos 5:8",
    "Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança. Gálatas 5:22",
    "Mas os que esperam no Senhor renovarão as suas forças e subirão com asas como águias; correrão e não se cansarão; caminharão e não se fatigarão. Isaías 40:31",
    "Na verdade, na verdade vos digo que quem ouve a minha palavra e crê naquele que me enviou tem a vida eterna e não entrará em condenação, mas passou da morte para a vida. João 5:24",
    "Não estejais inquietos por coisa alguma; antes, as vossas petições sejam em tudo conhecidas diante de Deus, pela oração e súplicas, com ação de graças. Filipenses 4:6",
    "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te esforço, e te ajudo, e te sustento com a destra da minha justiça. Isaías 41:10",
    "Não to mandei eu? Esforça-te e tem bom ânimo; não pasmes, nem te espantes, porque o Senhor, teu Deus, é contigo, por onde quer que andares. Josué 1:9",
    "A salvação não vem das obras, para que ninguém se glorie. Efésios 2:9",
    "Nem a altura, nem a profundidade, nem alguma outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus, nosso Senhor! Romanos 8:39",
    "Ninguém tem maior amor do que este: de dar alguém a sua vida pelos seus amigos. João 15:13",
    "Nisto todos conhecerão que sois meus discípulos, se vos amardes uns aos outros. João 13:35",
    "No princípio, criou Deus os céus e a terra. Gênesis 1:1",
    "No princípio, era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus. João 1:1",
    "O ladrão não vem senão a roubar, a matar e a destruir; eu vim para que tenham vida e a tenham com abundância. João 10:10",
    "O meu Deus, segundo as suas riquezas, suprirá todas as vossas necessidades em glória, por Cristo Jesus. Filipenses 4:19",
    "Oh! Quão bom e quão suave é que os irmãos vivam em união! Salmos 133:1",
    "Ora, a fé é o firme fundamento das coisas que se esperam e a prova das coisas que se não veem. Hebreus 11:1",
    "Ora, àquele que é poderoso para fazer tudo muito mais abundantemente além daquilo que pedimos ou pensamos, segundo o poder que em nós opera. Efésios 3:20",
    "Ora, o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pela virtude do Espírito Santo. Romanos 15:13",
    "Ora, sem fé é impossível agradar-lhe, porque é necessário que aquele que se aproxima de Deus creia que ele existe e que é galardoador dos que o buscam. Hebreus 11:6",
    "Ou não sabeis que o nosso corpo é o templo do Espírito Santo, que habita em vós, proveniente de Deus, e que não sois de vós mesmos? 1 Coríntios 6:19",
    "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna. João 3:16",
    "Porque Deus enviou o seu Filho ao mundo não para que condenasse o mundo, mas para que o mundo fosse salvo por ele. João 3:17",
    "Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação. 2 Timóteo 1:7",
    "Porque estou certo de que nem a morte, nem a vida, nem os anjos, nem os principados, nem as potestades, nem o presente, nem o porvir. Romanos 8:38",
    "Porque eu bem sei os pensamentos que penso de vós, diz o Senhor; pensamentos de paz e não de mal, para vos dar o fim que esperais. Jeremias 29:11",
    "Porque eu sou contigo, e ninguém lançará mão de ti para te fazer mal, pois tenho muito povo nesta cidade. Atos 18:10",
    "Porque não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas; porém um que, como nós, em tudo foi tentado, mas sem pecado. Hebreus 4:15",
    "Porque o meu jugo é suave, e o meu fardo é leve. Mateus 11:30",
    "Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna, por Cristo Jesus, nosso Senhor. Romanos 6:23",
    "Porque os meus pensamentos não são os vossos pensamentos, nem os vossos caminhos, os meus caminhos, diz o Senhor. Isaías 55:8",
    "Porque pela graça sois salvos, por meio da fé; e isso não vem de vós; é dom de Deus. Efésios 2:8",
    "Porque somos feitura sua, criados em Cristo Jesus para as boas obras, as quais Deus preparou para que andássemos nelas. Efésios 2:10",
    "Porque todos pecaram e destituídos estão da glória de Deus. Romanos 3:23",
    "Portanto, ide, ensinai todas as nações, batizando-as em nome do Pai, e do Filho, e do Espírito Santo. Mateus 28:19",
    "Posso todas as coisas naquele que me fortalece. Filipenses 4:13",
    "Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas. Provérbios 3:6",
    "Revesti-vos, pois, como eleitos de Deus, santos e amados, de entranhas de misericórdia, de benignidade, humildade, mansidão, longanimidade. Colossenses 3:12",
    "Rogo-vos, pois, irmãos, pela compaixão de Deus, que apresenteis o vosso corpo em sacrifício vivo, santo e agradável a Deus, que é o vosso culto racional. Romanos 12:1",
    "Sabendo que a prova da vossa fé produz a paciência. Tiago 1:3",
    "Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça. 1 João 1:9",
    "Sejam vossos costumes sem avareza, contentando-vos com o que tendes; porque ele disse: Não te deixarei, nem te desampararei. Hebreus 13:5",
    "Tendo por certo isto mesmo: que aquele que em vós começou a boa obra a aperfeiçoará até ao Dia de Jesus Cristo. Filipenses 1:6",
    "Tenho-vos dito isso, para que em mim tenhais paz; no mundo tereis aflições, mas tende bom ânimo; eu venci o mundo. João 16:33",
    "Toda Escritura divinamente inspirada é proveitosa para ensinar, para redarguir, para corrigir, para instruir em justiça. 2 Timóteo 3:16",
    "Todos nós andamos desgarrados como ovelhas; cada um se desviava pelo seu caminho, mas o Senhor fez cair sobre ele a iniquidade de nós todos. Isaías 53:6",
    "Tomai sobre vós o meu jugo, e aprendei de mim, que sou manso e humilde de coração, e encontrareis descanso para a vossa alma. Mateus 11:29",
    "Tu conservarás em paz aquele cuja mente está firme em ti; porque ele confia em ti. Isaías 26:3",
    "Verdadeiramente, ele tomou sobre si as nossas enfermidades e as nossas dores levou sobre si; e nós o reputamos por aflito, ferido de Deus e oprimido. Isaías 53:4",
    "Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei. Mateus 11:28",
    "Deem ao Senhor a glória devida ao seu nome. Tragam ofertas e venham à sua presença. Adorem o Senhor no esplendor da sua santidade. 1 Crônicas 16:29",
    "E por causa dele estais em Cristo Jesus, que se tornou para nós sabedoria de Deus, justiça, santificação e redenção. 1 Coríntios 1:30",
    "Antes que te formasse no ventre te conheci, e antes que nasceste te consagrei; Eu te designei um profeta para as nações. Jeremias 1: 5",
    "Educa a criança no caminho em que deve andar; e até quando envelhecer não se desviará dele. Provérbios 22:6",
    "Darei graças ao Senhor por sua justiça; ao nome do Senhor Altíssimo cantarei louvores. Salmos 7:17",
    "Ao único Deus sábio, Salvador nosso, seja glória e majestade, domínio e poder, agora, e para todo o sempre. Amém. Judas 1:25",
    "Porque todo o que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo, a nossa fé. 1 João 5:4",
    "Lâmpada para os meus pés é a tua palavra e, luz para o meu caminho. Salmo 119:105",
    "Por meio de Jesus, portanto, ofereçamos continuamente a Deus um sacrifício de louvor, que é fruto de lábios que confessam o seu nome. Hebreus 13:15",
    "Saiba que o Senhor, ele é Deus! Foi ele quem nos fez, e nós somos seus; nós somos o seu povo e as ovelhas do seu pasto. Salmos 100:3",
    "Portanto, acolhei-vos uns aos outros como Cristo vos acolheu, para glória de Deus. Romanos 15: 7",
    "Santo, santo, santo é o Senhor dos Exércitos, a terra inteira está cheia da sua glória. Isaías 6:3",
    "Cantem louvores ao Senhor, pois ele tem feito coisas gloriosas, sejam elas conhecidas em todo o mundo. Isaías 12:5",
    "Esta é a vida eterna: que te conheçam, o único Deus verdadeiro, e a Jesus Cristo, a quem enviaste. João 17:3",
    "Como podemos ser suficientemente gratos a Deus por vocês, por toda a alegria que temos diante dele por causa de vocês? 1 Tessalonicenses 3:9",
    "Eu e a minha casa serviremos ao Senhor. Josué 24:15",
    "Amarás, pois, o Senhor teu Deus de todo o teu coração, e de toda a tua alma, e de todas as tuas forças. Deuteronômio 6:5",
    "Era este menino que eu pedia, e o Senhor concedeu-me o pedido. 1 Samuel 1:27",
    "Não deixo de dar graças por vocês, mencionando-os em minhas orações. Efésios 1:16",
    "Toda boa dádiva e todo dom perfeito vêm do alto, descendo do Pai das luzes, que não muda como sombras inconstantes. Tiago 1:17",
    "O Senhor é o meu pastor; de nada terei falta. Salmos 23:1",
    "Assim, eles já não são dois, mas sim uma só carne. Portanto, o que Deus uniu, ninguém separe. Mateus 19:6",
    "Que diremos, pois, diante dessas coisas? Se Deus é por nós, quem será contra nós? Romanos 8:31",
    "Honra teu pai e tua mãe, a fim de que tenhas vida longa na terra que o Senhor, o teu Deus, te dá. Êxodo 20:12",
    "Quem ama seu irmão permanece na luz. 1 João 2:10",
    "Agradeço a meu Deus toda vez que me lembro de vocês. Filipenses 1:3",
    "Tudo posso naquele que me fortalece. Filipenses 4:13",
    "O amigo ama em todos os momentos; é um irmão na adversidade. Provérbios 17:17",
    "Um verdadeiro amigo é mais chegado que um irmão. Provérbios 18:24",
    "Melhor é o vizinho próximo do que o irmão distante. Provérbios 27:10",
    "Ninguém tem maior amor do que aquele que dá a sua vida pelos seus amigos. João 15:13",
    "Dediquem-se uns aos outros com amor fraternal. Prefiram dar honra aos outros mais do que a vocês. Romanos 12:10",
    "Jejuamos e suplicamos essa bênção ao nosso Deus, e ele nos atendeu. Esdras 8:23",
    "Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos. Provérbios 16:3",
    "O fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade. Gálatas 5:22",
    "Ao pôr do sol, o povo trouxe a Jesus todos os que tinham vários tipos de doenças; e ele os curou, impondo as mãos sobre cada um deles. Lucas 4:40",
    "O Senhor o protegerá e preservará a sua vida; O Senhor o susterá em seu leito de enfermidade, e da doença o restaurará. Salmos 41:2-3",
    "É Ele que perdoa todos os seus pecados e cura todas as suas doenças, que resgata a sua vida da sepultura e o coroa de bondade e compaixão. Salmos 103:3-4",
    "A sua fé a curou! Vá em paz e fique livre do seu sofrimento. Marcos 5:34",
    "Portanto, agora nenhuma condenação há para os que estão em Cristo Jesus. Romanos 8: 1",
    "Do Senhor vem o livramento. A tua bênção está sobre o teu povo. Salmos 3:8",
    "Tu me dás o teu escudo de livramento; a tua ajuda me fez forte. Neemias 9:31",
    "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará. Salmos 91:1",
    "O Senhor foi o meu amparo. Ele me deu total libertação; livrou-me porque me quer bem. Salmos 18:18-19",
    "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia. Salmos 46:1",
    "Ora, a fé é o firme fundamento das coisas que se esperam, e a prova das coisas que se não vêem. Hebreus 11:1",
    "Eu sou o pão da vida. João 6:48",
    "E disse-lhes: Ide por todo o mundo, pregai o evangelho a toda criatura. Marcos 16:15",
    "Perturbai-vos e não pequeis; falai com o vosso coração sobre a vossa cama, e calai-vos. Salmos 4:4",
    "Em paz também me deitarei e dormirei, porque só tu, Senhor, me fazes habitar em segurança. Salmos 4:8",
    "Se o Senhor não edificar a casa, em vão trabalham os que a edificam; se o Senhor não guardar a cidade, em vão vigia a sentinela. Salmos 127:1",
    "Bem-aventurado o homem que não anda segundo o conselho dos ímpios, nem se detém no caminho dos pecadores, nem se assenta na roda dos escarnecedores. Salmos 1:1",
    "Bem-aventurados os que choram, porque eles serão consolados. Mateus 5:4",
    "O temor do Senhor é o princípio do conhecimento; os loucos desprezam a sabedoria e a instrução. Provérbios 1:7",
    "Antes que te formasse no ventre te conheci, e antes que nasceste te consagrei; Eu te designei um profeta para as nações. Jeremias 1:5",
    "Direi do Senhor: Ele é o meu Deus, o meu refúgio, a minha fortaleza, e nele confiarei. Salmos 91:2",
    "Guarda-me como a menina do olho; esconde-me debaixo da sombra das tuas asas. Salmos 17:8",
    "O coração alegre aformoseia o rosto, mas pela dor do coração o espírito se abate. Provérbios 15:13",
    "Uns confiam em carros e outros em cavalos, mas nós faremos menção do nome do Senhor nosso Deus. Salmos 20:7",
    "Escondi a tua palavra no meu coração, para eu não pecar contra ti. Salmos 119:11",
    "Bem-aventurados os que choram, porque eles serão consolados. Mateus 5:4",
    "Disse-lhe Jesus: Eu sou o caminho, e a verdade e a vida; ninguém vem ao Pai, senão por mim. João 14:6",
    "Clame a mim e eu responderei e direi a você coisas grandiosas e insondáveis que você não conhece. Jeremias 33:3",
    "Deleite-se no Senhor, e ele atenderá aos desejos do seu coração. Salmos 37:4",
    "Alegrem-se sempre no Senhor. Novamente direi: Alegrem-se! Filipenses 4:4",
    "Quem examina cada questão com cuidado prospera, e feliz é aquele que confia no Senhor. Provérbios 16:20",
    "Como é feliz o homem a quem Deus corrige; portanto, não despreze a disciplina do Todo-poderoso. Jó 5:17",
    "E disse o senhor ao servo: Sai pelos caminhos e valados, e força-os a entrar, para que a minha casa se encha. Lucas 14:23",
    "Pois a palavra do Senhor é verdadeira; ele é fiel em tudo o que faz. Salmos 33:4",
    "Apeguemo-nos com firmeza à esperança que professamos, pois aquele que prometeu é fiel. Hebreus 10:23",
    "O ladrão não vem senão a roubar, a matar, e a destruir; eu vim para que tenham vida, e a tenham com abundância. João 10:10",
    "Pois a sua ira só dura um instante, mas o seu favor dura a vida toda; o choro pode persistir uma noite, mas de manhã irrompe a alegria. Salmos 30:5",
    "Provem e vejam como o Senhor é bom. Como é feliz o homem que nele se refugia! Salmos 34:8",
    "E, quando Eu me for e vos tiver preparado um lugar, virei de novo e vos levarei para mim, a fim de que, onde Eu estiver, estejais vós também. João 14:3",

  ];
  static var frasegerada = 'Clique para gerar um novo versículo!';
}

